### ISSUE TITLE
Subastar?

### ISSUE THREAD

**Issue by josibuttazzoni** [Santimaffini/TPs_Individuales_PdP2021#5]
```haskell
hacerBerrinchePor :: Propiedad -> Accion
hacerBerrinchePor propiedad jugador | dinero jugador >= snd propiedad = subastar propiedad jugador
                                    | otherwise = (hacerBerrinchePor propiedad).gritar.(cambiarDinero (+10)) $ jugador
```
Por que usaste subastar aca? Fijate que el enunciado dice  _Cuando una persona hace un berrinche por una propiedad se le suman $10 y se la hace gritar, la persona **sigue haciendo berrinche** hasta que llegue a comprar la propiedad que quiere._ 

La parte de **seguir haciendo** donde estaria en tu funcion?
Por otro lado, esta bueno delegar en funciones auxiliares (siempre que no sea una sobredelegacion) para que el codigo sea mas claro

**Comment by Santimaffini** [comment]
Ahora cambie subastar por adquirirPropiedad, pero no entiendo que estaria mal con lo de "seguir haciendo". Yo lo entendi como que hace berrinche tantas veces haga falta hasta que pueda comprar la propiedad, es decir que tenga el dinero necesario, que es lo que hace en el otherwise; por ej, si carolina quiere comprar una propiedad que sale 500 y tiene 470, va a hacer berrinche por eso 3 veces hasta que la compra, y se ve eso reflejado en que subio su dinero y se la hizo gritar 3 veces. No se si es que estoy entendiendo mal, pero ahi es donde estaria presente la recursividad.

**Comment by josibuttazzoni** [comment]
Sii, con `adquirirPropiedad` esta bien ahora, quedo mucho mejor. Tenes razón con lo de recursividad, no se que habré leído que no vi que estabas usando también `hacerBerrinchePor`, perdón!

**Comment by Santimaffini** [comment]
Ah listo! No pasa nada jaja, me quede pensandola y no se me ocurria otra forma
